name: Build

concurrency: 
  group: "build"
  cancel-in-progress: true

on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - '*.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: "src"

      - name: Checkout builds
        uses: actions/checkout@v4
        with:
          ref: "builds"
          path: "builds"
        continue-on-error: true
      
      - name: Create builds directory if it doesn't exist
        run: |
          if [ ! -d "builds" ]; then
            mkdir builds
            cd builds
            git init
            git remote add origin ${{ github.server_url }}/${{ github.repository }}
            git checkout -b builds
            touch .gitkeep
            git add .gitkeep
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            git commit -m "Initialize builds branch"
            git push origin builds
            cd ..
          fi

      - name: Clean old builds
        run: rm -f $GITHUB_WORKSPACE/builds/*.cs3

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build Plugins
        run: |
          cd $GITHUB_WORKSPACE/src
          chmod +x gradlew
          ./gradlew make makePluginsJson
          cp **/build/*.cs3 $GITHUB_WORKSPACE/builds/ 2>/dev/null || true
          cp build/plugins.json $GITHUB_WORKSPACE/builds/ 2>/dev/null || true

      - name: Push builds
        run: |
          cd $GITHUB_WORKSPACE/builds
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git diff --staged --quiet || git commit -m "Build $GITHUB_SHA"
          git push --set-upstream origin builds
